require("core.options") 
require("core.keymaps")
require("plugins.plugin")
require("plugins.lualine" ) 
require("plugins.nvimtree" ) 
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.gitsigns")
require("plugins.telescope")
